"""Remove data_source_type and add file_type and analysis_category

Revision ID: 30e4b32d0266
Revises: cd759832aba5
Create Date: 2025-07-11 04:58:54.869818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30e4b32d0266'
down_revision: Union[str, Sequence[str], None] = 'cd759832aba5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 首先创建新的枚举类型
    analysiscategory_enum = postgresql.ENUM('TEXTUAL', 'IMAGE', 'TABULAR', 'VIDEO', 'AUDIO', 'GEOSPATIAL', 'GRAPH', 'UNSTRUCTURED', name='analysiscategory')
    analysiscategory_enum.create(op.get_bind())
    
    # 添加新列
    op.add_column('data_sources', sa.Column('file_type', sa.String(), nullable=True))
    op.add_column('data_sources', sa.Column('analysis_category', analysiscategory_enum, nullable=True))
    
    # 删除旧列
    op.drop_column('data_sources', 'data_source_type')
    
    # 清理旧的枚举类型
    op.execute("DROP TYPE IF EXISTS data_source_type_enum CASCADE")
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 重新创建旧的枚举类型
    data_source_type_enum = postgresql.ENUM('csv', 'json', 'txt', 'pdf', 'image', 'video', 'audio', 'database', 'api', 'unknown', name='data_source_type_enum')
    data_source_type_enum.create(op.get_bind())
    
    # 添加旧列
    op.add_column('data_sources', sa.Column('data_source_type', data_source_type_enum, autoincrement=False, nullable=False))
    
    # 删除新列
    op.drop_column('data_sources', 'analysis_category')
    op.drop_column('data_sources', 'file_type')
    
    # 清理新的枚举类型
    op.execute("DROP TYPE IF EXISTS analysiscategory CASCADE")
    
    # ### end Alembic commands ###
