"""add uploaded_at to data_sources

Revision ID: 352d6933526e
Revises: d8a2b7f0c1e9
Create Date: 2025-07-07 16:25:19.970601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '352d6933526e'
down_revision: Union[str, Sequence[str], None] = 'd8a2b7f0c1e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Manually added to fix existing NULL values before applying NOT NULL constraint
    op.execute("UPDATE data_sources SET created_at = NOW() WHERE created_at IS NULL")
    op.execute("UPDATE data_sources SET updated_at = NOW() WHERE updated_at IS NULL")
    op.execute("UPDATE projects SET created_at = NOW() WHERE created_at IS NULL")
    op.execute("UPDATE projects SET updated_at = NOW() WHERE updated_at IS NULL")

    op.add_column('data_sources', sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True, comment='文件上传时间'))
    op.alter_column('data_sources', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('data_sources', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('data_sources', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('data_sources', 'profiling_result',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('data_sources', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               comment='创建时间')
    op.alter_column('data_sources', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               comment='最后更新时间')
    op.alter_column('data_sources', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='删除时间',
               existing_nullable=True)
    op.alter_column('data_sources', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment='是否被删除',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_data_sources_is_deleted'), table_name='data_sources')
    op.create_index(op.f('ix_data_sources_id'), 'data_sources', ['id'], unique=False)
    op.create_index(op.f('ix_data_sources_name'), 'data_sources', ['name'], unique=False)
    op.alter_column('projects', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('projects', 'status', server_default=None)
    op.alter_column('projects', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('ACTIVE', 'ARCHIVED', 'PENDING', 'DELETED', name='projectstatus'),
               existing_nullable=False,
               postgresql_using='status::projectstatus',
               server_default='ACTIVE')
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='最后更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='删除时间',
               existing_nullable=True)
    op.alter_column('projects', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment='是否被删除',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_projects_is_deleted'), table_name='projects')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_foreign_key(None, 'projects', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_index(op.f('ix_projects_is_deleted'), 'projects', ['is_deleted'], unique=False)
    op.alter_column('projects', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否被删除',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('projects', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='删除时间',
               existing_nullable=True)
    op.alter_column('projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='最后更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'status',
               existing_type=sa.Enum('ACTIVE', 'ARCHIVED', 'PENDING', 'DELETED', name='projectstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('projects', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_data_sources_name'), table_name='data_sources')
    op.drop_index(op.f('ix_data_sources_id'), table_name='data_sources')
    op.create_index(op.f('idx_data_sources_is_deleted'), 'data_sources', ['is_deleted'], unique=False)
    op.alter_column('data_sources', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否被删除',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('data_sources', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='删除时间',
               existing_nullable=True)
    op.alter_column('data_sources', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               comment=None,
               existing_comment='最后更新时间')
    op.alter_column('data_sources', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               comment=None,
               existing_comment='创建时间')
    op.alter_column('data_sources', 'profiling_result',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('data_sources', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('data_sources', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('data_sources', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('data_sources', 'uploaded_at')
    # ### end Alembic commands ###
