"""Add text analysis fields to data_sources

Revision ID: 3f593f272bfa
Revises: 55140254014a
Create Date: 2025-07-08 17:53:58.511587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f593f272bfa'
down_revision: Union[str, Sequence[str], None] = '55140254014a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_sources', sa.Column('keywords', sa.JSON(), nullable=True, comment='文本关键词列表'))
    op.add_column('data_sources', sa.Column('summary', sa.Text(), nullable=True, comment='文本摘要'))
    op.add_column('data_sources', sa.Column('sentiment', sa.JSON(), nullable=True, comment='情感分析结果'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_sources', 'sentiment')
    op.drop_column('data_sources', 'summary')
    op.drop_column('data_sources', 'keywords')
    # ### end Alembic commands ###
