"""Remove text analysis fields from data_sources

Revision ID: 4f8e862e67ff
Revises: 3f593f272bfa
Create Date: 2025-07-09 09:29:22.617493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f8e862e67ff'
down_revision: Union[str, Sequence[str], None] = '3f593f272bfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_sources', 'summary')
    op.drop_column('data_sources', 'keywords')
    op.drop_column('data_sources', 'sentiment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_sources', sa.Column('sentiment', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='情感分析结果'))
    op.add_column('data_sources', sa.Column('keywords', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='文本关键词列表'))
    op.add_column('data_sources', sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True, comment='文本摘要'))
    # ### end Alembic commands ###
