"""add_video_analysis_progress_fields

Revision ID: 776271eae874
Revises: 30e4b32d0266
Create Date: 2025-07-18 14:13:12.639365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '776271eae874'
down_revision: Union[str, Sequence[str], None] = '30e4b32d0266'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_analyses', sa.Column('current_phase', sa.String(), nullable=True, comment='当前分析阶段'))
    op.add_column('video_analyses', sa.Column('progress_percentage', sa.Float(), nullable=True, comment='进度百分比'))
    op.add_column('video_analyses', sa.Column('progress_message', sa.String(), nullable=True, comment='进度消息'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_analyses', 'progress_message')
    op.drop_column('video_analyses', 'progress_percentage')
    op.drop_column('video_analyses', 'current_phase')
    # ### end Alembic commands ###
