"""add image_hash to data_sources

Revision ID: 866c454824bf
Revises: bfa1d2cba5f7
Create Date: 2025-07-08 11:57:35.697551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '866c454824bf'
down_revision: Union[str, Sequence[str], None] = 'bfa1d2cba5f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_sources', sa.Column('image_hash', sa.String(), nullable=True))
    op.create_index(op.f('ix_data_sources_image_hash'), 'data_sources', ['image_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_sources_image_hash'), table_name='data_sources')
    op.drop_column('data_sources', 'image_hash')
    # ### end Alembic commands ###
