"""Refactor DataSource with file_type and analysis_category

Revision ID: cd759832aba5
Revises: 4f8e862e67ff
Create Date: 2025-07-11 04:52:34.440021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd759832aba5'
down_revision: Union[str, Sequence[str], None] = '4f8e862e67ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
